const DashboardRoutes = [
    '/municipalidad/dashboard',
    '/empresa/dashboard',
    '/municipalidad/dashboard/perfil',
    '/empresa/dashboard/perfil',
    '/municipalidad/dashboard/usuarios',
    '/empresa/dashboard/usuarios',
    '/municipalidad/dashboard/posicion',
    '/empresa/dashboard/posicion',
    '/municipalidad/dashboard/postulantes',
    '/empresa/dashboard/postulantes',
    '/municipalidad/dashboard/postulante/perfil/:postulant_id',
    '/empresa/dashboard/postulante/perfil/:postulant_id',
    '/municipalidad/dashboard/ver-posicion',
    '/empresa/dashboard/ver-posicion',
    '/empresa/dashboard/cambiar-password',
    '/municipalidad/dashboard/cambiar-password',
    '/empresa/dashboard/historial-de-publicaciones',
    '/municipalidad/dashboard/historial-de-publicaciones',
    '/empresa/dashboard/republicar-posicion',
    '/municipalidad/dashboard/republicar-posicion',
    '/empresa/dashboard/ver-detalles-de-posicion',
    '/municipalidad/dashboard/ver-detalles-de-posicion',
];
export default DashboardRoutes;