export const ApplicantType = {
    SET_PUBLICATIONS_ACCOUNT: 'APPLICANT/SET_PUBLICATIONS_ACCOUNT',
    SET_PUBLICATIONS_ACCOUNT_ERROR: 'APPLICANT/SET_PUBLICATIONS_ACCOUNT_ERROR',
    SET_PUBLICATION_SELECTED: 'APPLICANT/SET_PUBLICATION_SELECTED',
    SET_STATUS: 'APPLICANT/SET_STATUS',
};
