export const ApplicantType  = {
    SET_PUBLICATIONS_ACCOUNT: 'SET_PUBLICATIONS_ACCOUNT',
    SET_PUBLICATIONS_ACCOUNT_ERROR: 'SET_PUBLICATIONS_ACCOUNT_ERROR',
    SET_PUBLICATION_SELECTED: 'SET_PUBLICATION_SELECTED',
};
