
export const HOME = '/'
export const REGISTER = '/registro'
export const RESTOREPASS = '/restablecer-contraseña'
export const NOTIFICATIONPASS = '/notificacion-contraseña'
export const NEWPASSWORD = '/nueva-contraseña'
export const LOGIN = '/inicio-sesion'
export const WELCOME = '/inicio'
export const INFO = '/info'
export const INFOADRESS = '/info-direccion'
export const INFOEXPERIENCE = '/info-experiencia'
